### ISSUE TITLE
Include TypeScript stack (cds-routing-handlers)

### ISSUE THREAD

**Issue by hakimio** [SAP-samples/cap-sflight#13]
It would be nice if there was also TypeScript example using [cds-routing-handlers](https://github.com/mrbandler/cds-routing-handlers). I imagine it should be a bit similar to the [Java one](https://github.com/SAP-samples/cap-sflight/pull/5).

**Comment by tsteckenborn** [comment]
With TypeScript support not being officially there yet, I guess that‘s nothing for the SAP-samples. Also SAP might go in a different direction compared to cds-routing-handlers, see the cap-samples repository. In there you might find a quick look at something called cds-ts, which is not yet released to us, the public.

Let‘s see what this months release will bring to us 😉

**Comment by hakimio** [comment]
@tsteckenborn can you link the repository?

**Comment by tsteckenborn** [comment]
@hakimio: You might start here https://github.com/SAP-samples/cloud-cap-samples/pull/245.

**Comment by hakimio** [comment]
Any documentation or other examples for `cds-ts`? The linked PR looks like it only contains "hello world" code.

**Comment by tsteckenborn** [comment]
That‘s right. To my knowledge, no. As I said it‘s not even released to public yet. Therefor I guess that the request to include a TypeScript sample with cds-routing-handlers will not be fulfilled.

**Comment by hakimio** [comment]
News about `cds-ts`:
https://www.youtube.com/watch?v=P5TVj6YDC1c&t=53s
https://cap.cloud.sap/docs/releases/july21#on-the-fly-typescript-with-cds-ts

**Comment by iwonahahn** [comment]
The issue seems to be resolved and we are about to close this issue channel here in favor of the SAP Community.
In case you still need support, use our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) to get help.
