### ISSUE TITLE
Fiori UI not available when running locally with Java

### ISSUE THREAD

**Issue by hawklwd** [SAP-samples/cap-sflight#1314]
Dear Expert ,
I just git pull the latest version of SFLIGHT, try to run the java world . 
after `npm ci`, I can execute the CAP by command `mvn spring-boot:run`. 
But the frontpage can't be open anymore. I found you update the js -> ts recently. 
The browser type below error message. 
```
 Refused to execute script from 'http://localhost:4004/travel_processor/webapp/Component.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
Component.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
index.html:1  Refused to execute script from 'http://localhost:4004/travel_processor/webapp/Component.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
Log-dbg.js:497  2024-12-06 16:51:14.861000 failed to load JavaScript resource: sap/fe/cap/travel/Component.js -  sap.ui.ModuleSystem
u @ Log-dbg.js:497
Log-dbg.js:497  2024-12-06 16:51:14.862000 [FUTURE FATAL] Failed to load component for container container - ModuleError: failed to load 'sap/fe/cap/travel/Component.js' from ./Component.js: script load error  
 ModuleError: failed to load 'sap/fe/cap/travel/Component.js' from ./Component.js: script load error
    at ve (https://ui5.sap.com/1.130.2/resources/sap-ui-core.js:10:6909)
    at he.failWith (https://ui5.sap.com/1.130.2/resources/sap-ui-core.js:10:4785)
    at HTMLScriptElement.i (https://ui5.sap.com/1.130.2/resources/sap-ui-core.js:10:10762)
Caused by: Error: script load error
    at HTMLScriptElement.i (https://ui5.sap.com/1.130.2/resources/sap-ui-core.js:10:10804)Caused by: Error: script load error
    at HTMLScriptElement.i (ui5loader-dbg.js:1487:55
```

**Comment by Akatuoro** [comment]
@c-kobo , @chgeo , is there any possibility to start the ui5 typescript handling in parallel for the java app? To my understanding this is handled by the `cds-plugin-ui5` package in node.js.

@hawklwd , a workaround is to change the [dataSource.mainService.uri](https://github.com/SAP-samples/cap-sflight/blob/86f336a02ea30d3a501ce93efcb761ff72d28e8b/app/travel_processor/webapp/manifest.json#L22) into an absolute url, then do an `npm run build` inside `app/travel_processor` and navigate to http://localhost:4004/travel_processor/dist/index.html

**Comment by chgeo** [comment]
> a workaround is to change the [dataSource.mainService.uri](https://github.com/SAP-samples/cap-sflight/blob/86f336a02ea30d3a501ce93efcb761ff72d28e8b/app/travel_processor/webapp/manifest.json#L22) into an absolute url, then do an `npm run build` inside `app/travel_processor` and navigate to http://localhost:4004/travel_processor/dist/index.html

Better workaround is in https://github.com/SAP-samples/cap-sflight/pull/1315

**Comment by chgeo** [comment]
@hawklwd  In general, we don't have a good roundtrip for Java at the moment.  You need to build the UI before you can use it.  I have adjusted the documentation in #1315.

**Comment by chgeo** [comment]
@stewsk This is something for the next SFlight meeting.

**Comment by hawklwd** [comment]
Thank you for your update,  it works fine for me
