### ISSUE TITLE
Unauthorized error on BTP/CF

### ISSUE THREAD

**Issue by techaware** [SAP-samples/cap-sflight#28]
After cf deploy mta_archives/capire.sflight_1.0.0.mtar when I run the service in BTP, and click any entity it gives a 401 Unauthorized error. 

<error xmlns="http://docs.oasis-open.org/odata/ns/metadata">
<code>401</code>
<message>Unauthorized</message>
</error>

Am I missing some details? Kindly advice. 

@rbrechter @stewsk

**Comment by iwonahahn** [comment]
We are about to close this issue channel here in favor of the SAP Community.
In case you still need support, use our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) to get help.
