### ISSUE TITLE
A technical error has occurred with the now default SAPUI5 1.95.0

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/cap-sflight#42]
Hello SAP CAP Team,

yesterday SAPUI5 1.95.0 was made the default in the CDN. when Starting the sample app the following error occurs:

```
A technical error has occurred.
this._oAppComponent.getRootControl(...).getController(...).getPlaceholder is not a function
```

Best Regards
Gregor

**Comment by iwonahahn** [comment]
Hi Gregor,

Is this issue still open? We are about to close this issue channel here in favor of the SAP Community.
In case you still need support, use our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) to get help.

Best regards,
Iwona
